version: "2"

services:
  nginx:
    container_name: nginx-proxy-server
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    links:
      - api:api
    ports:
      - "80:80"
      - "443:443"
    networks:
      - fcc-network

  api:
    container_name: api-backend
    build:
      context: ./api
    ports:
      - "3000"
    networks:
      - fcc-network

networks:
  fcc-network:
    driver: bridge