version: "2"

services:
  nginx:
    container_name: nginx-proxy-server
    build:
      context: nginx
    links:
      - web:web
    ports:
      - "80:80"
      - "443:443"
    networks:
      - fcc-network

  web:
    container_name: web-frontend
    build:
      context: web
    ports:
      - "3000"
    networks:
      - fcc-network

networks:
  fcc-network:
    driver: bridge